### ISSUE TITLE
make file error

### ISSUE THREAD

**Issue by htran170642** [AdityaVarmaUddaraju/Helmet-Detection#3]
![image](https://user-images.githubusercontent.com/70887055/120169653-60009d00-c22a-11eb-8971-1fa4144d0a21.png)

Hi, I got this error when running cmd make. How can I fix it? Thank you so much.

**Comment by AdityaVarmaUddaraju** [comment]
can you specify more about your environmnet
ubuntu os version
deepstream
cuda
tensorrt

**Comment by htran170642** [comment]
![image](https://user-images.githubusercontent.com/70887055/120176798-e8367080-c231-11eb-85ea-7a8f0ed7447a.png)

I use ds 5.1, cuda 10.2
I 've got new error. Any idea to fix it? Thank yo so much.
